config/routes.rb
Rails.application.routes.draw do
  resources :webhooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/webhook.rb
class Webhook < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :set_webhook, only: [:show, :edit, :update, :destroy]

  # GET /webhooks
  # GET /webhooks.json
  def index
    @webhooks = Webhook.all
  end

  # GET /webhooks/1
  # GET /webhooks/1.json
  def show
  end

  # GET /webhooks/new
  def new
    @webhook = Webhook.new
  end

  # GET /webhooks/1/edit
  def edit
  end

  # POST /webhooks
  # POST /webhooks.json
  def create
    @webhook = Webhook.new(webhook_params)

    respond_to do |format|
      if @webhook.save
        format.html { redirect_to @webhook, notice: 'Webhook was successfully created.' }
        format.json { render :show, status: :created, location: @webhook }
      else
        format.html { render :new }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhooks/1
  # PATCH/PUT /webhooks/1.json
  def update
    respond_to do |format|
      if @webhook.update(webhook_params)
        format.html { redirect_to @webhook, notice: 'Webhook was successfully updated.' }
        format.json { render :show, status: :ok, location: @webhook }
      else
        format.html { render :edit }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhooks/1
  # DELETE /webhooks/1.json
  def destroy
    @webhook.destroy
    respond_to do |format|
      format.html { redirect_to webhooks_url, notice: 'Webhook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook
      @webhook = Webhook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webhook_params
      params.require(:webhook).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntelipostApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/webhooks/_form.html.erb
<%= form_with(model: webhook, local: true) do |form| %>
  <% if webhook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webhook.errors.count, "error") %> prohibited this webhook from being saved:</h2>

      <ul>
      <% webhook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webhooks/edit.html.erb
<h1>Editing Webhook</h1>

<%= render 'form', webhook: @webhook %>

<%= link_to 'Show', @webhook %> |
<%= link_to 'Back', webhooks_path %>

app/views/webhooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webhooks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webhooks.each do |webhook| %>
      <tr>
        <td><%= webhook.name %></td>
        <td><%= webhook.url %></td>
        <td><%= link_to 'Show', webhook %></td>
        <td><%= link_to 'Edit', edit_webhook_path(webhook) %></td>
        <td><%= link_to 'Destroy', webhook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webhook', new_webhook_path %>

app/views/webhooks/new.html.erb
<h1>New Webhook</h1>

<%= render 'form', webhook: @webhook %>

<%= link_to 'Back', webhooks_path %>

app/views/webhooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @webhook.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @webhook.url %>
</p>

<%= link_to 'Edit', edit_webhook_path(@webhook) %> |
<%= link_to 'Back', webhooks_path %>